config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'

  resources :phones
  resources :users, only: %i[index edit update]

  namespace :api do
    namespace :webhooks do
      resource :telnyx, only: [:create], controller: 'telnyx'
    end
  end
end

app/controllers/phones_controller.rb
# frozen_string_literal: true

class PhonesController < ApplicationController
  before_action :require_signin
  before_action :find_phone, only: %i[edit update destroy]

  def index
    @phones = current_user.phone_numbers.kept.order(:created_at)
  end

  def new
    @phone = current_user.phone_numbers.build
  end

  def create
    @phone = current_user.phone_numbers.build(phone_params)

    if @phone.save
      flash.now[:success] = 'Phone created! It will be ready for usage soon.'

      respond_to do |f|
        f.turbo_stream
        f.html { redirect_to phones_path }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @phone.update(update_phone_params)
      flash.now[:info] = 'Phone successfully updated!'

      respond_to do |f|
        f.turbo_stream
        f.html { redirect_to phones_path }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @phone.discard!

    respond_to do |f|
      f.turbo_stream
      f.html { redirect_to phones_path }
    end
  end

  private

  def phone_params
    params.require(:user_phone_number).permit(:name, :area_code)
  end

  def update_phone_params
    params.require(:user_phone_number).permit(:name)
  end

  def find_phone
    @phone = current_user.phone_numbers.kept.find(params[:id])
  end
end

app/views/phones/_empty_phones.html.erb
<div class="bg-white overflow-hidden shadow rounded-lg">
  <div class="px-4 py-5 sm:p-6">
    <div class="text-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No phone numbers yet</h3>
      <p class="mt-1 text-sm text-gray-500">Get started by creating a phone number.</p>
    </div>
  </div>
</div>

app/views/phones/_form.html.erb
<div class="<%= phone.persisted? ? 'edit_phone' : 'new_phone' %>">
  <% if phone.errors.any? %>
    <div class="rounded-md bg-red-50 p-4 mb-6">
      <div class="flex">
        <div class="flex-shrink-0">
          <!-- Heroicon name: solid/x-circle -->
          <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <h3 class="text-sm font-medium text-red-800">There were <%= phone.errors.count %> errors with your submission</h3>
          <div class="mt-2 text-sm text-red-700">
            <ul role="list" class="list-disc pl-5 space-y-1">
              <% phone.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= form_with(model: phone, url: phone.persisted? ? phone_path(phone) : phones_path) do |f| %>
    <div class="input_container <%= 'with_error' if phone.errors.has_key?(:name) %>">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "My favorit number", autofocus: true, required: true %>
    </div>
    <% unless phone.persisted? %>
      <div class="input_container <%= 'with_error' if phone.errors.has_key?(:area_code) %>">
        <%= f.label :area_code %>
        <%= f.text_field :area_code, placeholder: "216", required: true %>
      </div>
    <% end %>

    <div>
      <%= f.submit phone.persisted? ? 'Update' : 'Create', class: "button--primary" %>
      <%= link_to 'Cancel', phones_path, class: 'button--default' %>
    </div>
  <% end %>
</div>

app/views/phones/create.turbo_stream.erb
<%= turbo_stream.append "phones", @phone %>

<%= turbo_stream.replace "new_phone" do %>
  <%= turbo_frame_tag "new_phone" do %>
    <div class="flex flex-row-reverse mb-4">
      <%= link_to "New phone number", new_phone_path, class: "button--primary" %>
    </div>
  <% end %>
<% end %>

<%= turbo_stream.replace "empty_phones" do %>
  <%= turbo_frame_tag "empty_phones" %>
<% end %>


<%= render_flash_stream %>

app/views/phones/destroy.turbo_stream.erb
<%= turbo_stream.remove @phone %>
<% if current_user.phone_numbers.kept.empty? %>
  <%= turbo_stream.replace "empty_phones" do %>
    <%= turbo_frame_tag "empty_phones" do%>
      <%= render 'empty_phones' %>
    <% end %>
  <% end %>
<% end %>

app/views/phones/edit.html.erb
<% content_for :title, "Edit phone number" %>

<div class="edit_phone_container">
  <div class="px-4 py-5 sm:p-6">
    <%= turbo_frame_tag @phone, class: "container" do %>
      <%= render "form", phone: @phone %>
    <% end %>
  </div>
</div>

app/views/phones/index.html.erb
<% content_for :title, "Phone numbers" %>

<%= turbo_frame_tag "new_phone" do %>
  <div class="flex flex-row-reverse mb-4">
    <%= link_to "New phone number", new_phone_path, class: "button--primary" %>
  </div>
<% end %>

<%= turbo_frame_tag "phones" do %>
  <%= render @phones %>
<% end %>

<%= turbo_frame_tag "empty_phones" do %>
  <% if @phones.empty? %>
    <%= render 'empty_phones' %>
  <% end %>
<% end %>

app/views/phones/new.html.erb
<% content_for :title, "New phone number" %>

<%= turbo_frame_tag "new_phone" do %>
  <div class="new_phone_container">
    <div class="px-4 py-5 sm:p-6">
      <%= render "form", phone: @phone %>
    </div>
  </div>
<% end %>

app/views/phones/update.turbo_stream.erb
<%= turbo_stream.replace @phone %>
<%= render_flash_stream %>