config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'

  resources :phones
  resources :users, only: %i[index edit update]

  namespace :api do
    namespace :webhooks do
      resource :telnyx, only: [:create], controller: 'telnyx'
    end
  end
end

app/models/user_phone_number.rb
# frozen_string_literal: true

class UserPhoneNumber < ApplicationRecord
  include Discard::Model

  belongs_to :user
  has_many :dialogs, dependent: :destroy

  enum status: {
    draft: 0,
    ready: 10,
    error: 20
  }

  validates :name, :area_code, presence: true
  validates :area_code, length: { is: 3 }, numericality: { only_integer: true }
  validates :name, uniqueness: { scope: :user_id, conditions: -> { kept } }

  # TODO: REMOVE IT AFTER STATUS UPDATE IMPLEMENTED, PLZ
  # I'M BEGGING YOU!!!!!
  after_update if: proc { status_changed? } do
    Rails.cache.delete("ready_numbers_for_#{user.id}")
    Rails.cache.delete("#{user.id}_has_ready_number")
  end
end

app/helpers/user_phone_numbers_helper.rb
# frozen_string_literal: true

module UserPhoneNumbersHelper
  BASE_URL = 'https://avatars.dicebear.com/api/'

  def user_phone_logo_url(phone)
    [
      BASE_URL,
      'initials',
      '/',
      CGI.escape([phone.name, phone.id].join),
      '.svg'
    ].join
  end
end

app/views/user_phone_numbers/_user_phone_number.html.erb
<% phone = user_phone_number %>

<%= turbo_frame_tag phone, class: "container" do %>
  <%= turbo_stream_from(phone) if phone.draft? %>
  <div class="top_wrapper">
    <%= button_to phone_path(phone), class: "remove", method: :delete, form: { data: { turbo_confirm: "Are you sure?"}} do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
      </svg>
    <% end %>
    <div class="info_wrapper">
      <div>
        <h3><%= phone.name %></h3>
        <span class="<%= phone.status %>">
          <svg fill="currentColor" viewBox="0 0 8 8">
            <circle cx="4" cy="4" r="3" />
          </svg>
          <%= phone.status %>
        </span>
      </div>
      <p><%= phone.number %></p>
    </div>
    <%= image_tag user_phone_logo_url(phone) %>
  </div>
  <div>
    <div class="actions_wrapper">
      <div class="edit">
        <%= link_to edit_phone_path(phone) do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
          <span>Edit</span>
        <% end %>
      </div>
      <div class="start">
        <% link_args = phone.ready? ? [convos_path(start_for: phone.id), data: {'turbo-frame': "_top"}] : ["", class: "disabled_link"] %>
        <%= link_to(*link_args) do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
          </svg>
          <span>Start messaging</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>