config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sessions', to: 'sessions#destroy'

  resources :phones
  resources :users, only: %i[index edit update]

  namespace :api do
    namespace :webhooks do
      resource :telnyx, only: [:create], controller: 'telnyx'
    end
  end
end

app/views/layouts/_flash.html.erb
<div class="flashes">
  <% flash.each do |type, message| %>
    <div class="flash_container <%= type %>" data-controller="flash">
      <div class="wrapper">
        <div class="icon_wrapper">
          <!-- Heroicon name: solid/check-circle -->
          <%= render "layouts/flash_icons/#{type}" %>
        </div>
        <div class="text_wrapper">
          <p><%= message %></p>
        </div>
        <div class="close_wrapper">
          <div>
            <button type="button" data-action="flash#close">
              <span class="sr-only">Dismiss</span>
              <!-- Heroicon name: solid/x -->
              <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="header">
  <div class="container">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="logo-container">
          <%= image_tag "mini-logo.svg", class: "block lg:hidden h-8 w-auto", alt: "ShalahMe" %>
          <%= image_tag "horizontal-logo.svg", class: "hidden lg:block h-8 w-auto", alt: "ShalahMe" %>
        </div>
        <div class="nav">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300" -->
          <% if signed_in? %>
            <%= nav_link_to "Dashboard", root_path, class: "item" %>
            <%= nav_link_to "Phone numbers", phones_path, class: "item" %>
            <%= nav_link_to "Convos", convos_path, class: "item" %>
            <% if allowed_to?(:index?, current_user) %>
              <%= nav_link_to "Users", users_path, class: "item" %>
            <% end %>
          <% else %>
            <%= nav_link_to "Home", root_path, class: "item" %>
          <% end %>
        </div>
      </div>
      <% if signed_in? %>
        <div class="profile">
          <!-- Profile dropdown -->
          <div class="ml-3 relative">
            <div>
              <button type="button" class="pic-button" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <%= image_tag current_user.logo_url, class: "h-8 w-8 rounded-full" %>
              </button>
            </div>

            <!--
              Dropdown menu, show/hide based on menu state.

              Entering: "transition ease-out duration-200"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
            -->
            <div class="dropdown hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" data-controller="header-menu" data-header-menu-trigger-value="user-menu-button">
              <!-- Active: "bg-gray-100", Not Active: "" -->

              <%= link_to "Sign out", sessions_path, class: "item", role: "menuitem" %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="login-buttons">
          <%= link_to "/auth/google_oauth2", class: "item", data: {turbo: false} do %>
            Sign in with Google
            <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <title>Google</title>
              <path d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"/>
            </svg>
          <% end %>
          <%= link_to "/auth/github", class: "item", data: {turbo: false} do %>
            Sign in with Github
            <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <title>GitHub</title>
              <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
            </svg>
          <% end %>
        </div>
      <% end %>
      <div class="-mr-2 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="mobile-button" id="mobile-menu-button" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            eroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="nav-mobile hidden" data-controller="header-menu" data-header-menu-trigger-value="mobile-menu-button" aria-labelledby="mobile-menu-button">
    <div class="nav">
      <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
      <% if signed_in? %>
        <%= nav_link_to "Dashboard", root_path, class: "item" %>
        <%= nav_link_to "Phone numbers", phones_path, class: "item" %>
        <%= nav_link_to "Convos", convos_path, class: "item" %>
        <% if allowed_to?(:index?, current_user) %>
          <%= nav_link_to "Users", users_path, class: "item" %>
        <% end %>
      <% else %>
        <%= nav_link_to "Home", root_path, class: "item" %>
      <% end %>
    </div>
    <% if signed_in? %>
      <div class="profile">
        <div class="info">
          <div class="image">
            <%= image_tag current_user.logo_url, alt: "Profile image" %>
          </div>
          <div class="info-container">
            <div class="name"><%= current_user.name %></div>
            <div class="email"><%= current_user.email %></div>
          </div>
        </div>
        <div class="actions">
          <%= link_to "Sign out", sessions_path, class: "item" %>
        </div>
      </div>
    <% else %>
      <div class="login-buttons">
        <%= link_to "/auth/google_oauth2", class: "item", data: {turbo: false} do %>
          Sign in with Google
          <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <title>Google</title>
            <path d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"/>
          </svg>
        <% end %>
        <%= link_to "/auth/github", class: "item", data: {turbo: false} do %>
          Sign in with Github
          <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <title>GitHub</title>
            <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
          </svg>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_loader.html.erb
<div class="flex justify-center items-center">
  <svg role="status" class="w-8 h-8 mr-2 text-gray-200 animate-spin fill-blue-700" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
  </svg>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>Shalahme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <div id="<%= content_id %>" class="min-h-full">
      <%= render "layouts/header" %>
      <%= turbo_frame_tag "redirects" %>

      <div id="flash">
        <%= render "layouts/flash" %>
      </div>

      <div class="py-10">
        <% if content_for :title %>
          <header>
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <h1 class="text-3xl font-bold leading-tight text-gray-900">
                <%= content_for :title %>
              </h1>
            </div>
          </header>
        <% end %>
        <main>
          <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <%= yield %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>